import $ from 'jquery';
import store from '../store/store';

// Detail management
export let EMAIL_MODIFIED = 'EMAIL_MODIFIED';
export let PASSWORD_MODIFIED = 'PASSWORD_MODIFIED';
export let SUBMIT_PRESSED = 'SUBMIT_PRESSED'

// States of creation
export let CREATE_CATTLE_CAMERA_INIT = 'CREATE_CATTLE_CAMERA_INIT';
export let CREATE_CATTLE_CAMERA_CAPTURE = 'CREATE_CATTLE_CAMERA_CAPTURE';
export let CREATE_CATTLE_ENTER_DETAILS = 'CREATE_CATTLE_ENTER_DETAILS';
export let CREATE_CATTLE_CREATE_SUCCESS = 'CREATE_CATTLE_CREATE_SUCCESS';
export let CREATE_CATTLE_CREATE_FAIL = 'CREATE_CATTLE_CREATE_FAIL';
export let CREATE_CATTLE_CANCEL = 'CREATE_CATTLE_CANCEL';



